<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountTreeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('account_trees')->insert([
            [
                'id' => 1,
                'emp_id' => 1,
                'name_ar' => 'الاصول',
                'name_en' => 'Assets',
                'parent_id' => NULL,
                'type' => 1,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:25:42',
                'updated_at' => '2024-06-04 09:25:42'
            ],
            [
                'id' => 2,
                'emp_id' => 1,
                'name_ar' => 'الخصوم',
                'name_en' => 'Adversaries',
                'parent_id' => NULL,
                'type' => 1,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:26:52',
                'updated_at' => '2024-06-04 09:26:52'
            ],
            [
                'id' => 3,
                'emp_id' => 1,
                'name_ar' => 'حقوق الملكيه',
                'name_en' => 'Property rights',
                'parent_id' => NULL,
                'type' => 1,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:28:39',
                'updated_at' => '2024-06-04 09:28:39'
            ],
            [
                'id' => 4,
                'emp_id' => 1,
                'name_ar' => 'الاصول الثابته',
                'name_en' => 'Fixed assets',
                'parent_id' => 1,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:29:55',
                'updated_at' => '2024-06-04 09:29:55'
            ],
            [
                'id' => 5,
                'emp_id' => 1,
                'name_ar' => 'الاصول المتداوله',
                'name_en' => 'Assets',
                'parent_id' => 1,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:30:43',
                'updated_at' => '2024-06-04 09:30:43'
            ],
            [
                'id' => 6,
                'emp_id' => 1,
                'name_ar' => 'الاصول الغير ملموسه',
                'name_en' => 'Intangible assets',
                'parent_id' => 1,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:31:34',
                'updated_at' => '2024-06-04 09:31:34'
            ],
            [
                'id' => 7,
                'emp_id' => 1,
                'name_ar' => 'الخصوم قصيره الاجل',
                'name_en' => 'Short-term liabilities',
                'parent_id' => 2,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:33:49',
                'updated_at' => '2024-06-04 09:33:49'
            ],
            [
                'id' => 8,
                'emp_id' => 1,
                'name_ar' => 'الخصوم طويله الاجل',
                'name_en' => 'Long-term liabilities',
                'parent_id' => 2,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:34:24',
                'updated_at' => '2024-06-04 09:34:24'
            ],
            [
                'id' => 9,
                'emp_id' => 1,
                'name_ar' => 'راس المال',
                'name_en' => 'capital',
                'parent_id' => 3,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:35:09',
                'updated_at' => '2024-06-04 09:35:09'
            ],
            [
                'id' => 10,
                'emp_id' => 1,
                'name_ar' => 'الارباح المرحله',
                'name_en' => 'Moving profits',
                'parent_id' => 3,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:40:57',
                'updated_at' => '2024-06-04 09:40:57'
            ],
            [
                'id' => 11,
                'emp_id' => 1,
                'name_ar' => 'ارباح العام',
                'name_en' => 'Years profits',
                'parent_id' => 3,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:41:54',
                'updated_at' => '2024-06-04 09:41:54'
            ],
            [
                'id' => 12,
                'emp_id' => 1,
                'name_ar' => 'جارى الشركاء',
                'name_en' => 'Partners are running',
                'parent_id' => 3,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:42:31',
                'updated_at' => '2024-06-04 09:42:31'
            ],
            [
                'id' => 13,
                'emp_id' => 1,
                'name_ar' => 'الاحتياطيات',
                'name_en' => 'Reserves',
                'parent_id' => 3,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:43:14',
                'updated_at' => '2024-06-04 09:43:14'
            ],
            [
                'id' => 14,
                'emp_id' => 1,
                'name_ar' => 'الايرادات',
                'name_en' => 'Revenues',
                'parent_id' => NULL,
                'type' => 1,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:44:19',
                'updated_at' => '2024-06-04 09:44:19'
            ],
            [
                'id' => 15,
                'emp_id' => 1,
                'name_ar' => 'المصروفات',
                'name_en' => 'Expenses',
                'parent_id' => NULL,
                'type' => 1,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:44:52',
                'updated_at' => '2024-06-04 09:44:52'
            ],
            [
                'id' => 16,
                'emp_id' => 1,
                'name_ar' => 'ايرادات النشاط',
                'name_en' => 'Activity revenues',
                'parent_id' => 14,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:45:37',
                'updated_at' => '2024-06-04 09:45:37'
            ],
            [
                'id' => 17,
                'emp_id' => 1,
                'name_ar' => 'ايرادات اخرى-راسماليه',
                'name_en' => 'Other capital revenues',
                'parent_id' => 14,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:46:28',
                'updated_at' => '2024-06-04 09:46:28'
            ],
            [
                'id' => 18,
                'emp_id' => 1,
                'name_ar' => 'مصروفات اداريه وعموميه',
                'name_en' => 'General and administrative expenses',
                'parent_id' => 15,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:47:14',
                'updated_at' => '2024-06-04 09:47:14'
            ],
            [
                'id' => 19,
                'emp_id' => 1,
                'name_ar' => 'مصروفات تشغيليه',
                'name_en' => 'Operating expenses',
                'parent_id' => 15,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:47:54',
                'updated_at' => '2024-06-04 09:47:54'
            ],
            [
                'id' => 20,
                'emp_id' => 1,
                'name_ar' => 'الاراضي',
                'name_en' => 'Lands',
                'parent_id' => 4,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:53:02',
                'updated_at' => '2024-06-04 09:53:02'
            ],
            [
                'id' => 21,
                'emp_id' => 1,
                'name_ar' => 'الالات',
                'name_en' => 'The machines',
                'parent_id' => 4,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:53:32',
                'updated_at' => '2024-06-04 09:53:32'
            ],
            [
                'id' => 22,
                'emp_id' => 1,
                'name_ar' => 'المعدات',
                'name_en' => 'hardware',
                'parent_id' => 4,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:54:43',
                'updated_at' => '2024-06-04 09:54:43'
            ],
            [
                'id' => 23,
                'emp_id' => 1,
                'name_ar' => 'المباني',
                'name_en' => 'Buildings',
                'parent_id' => 4,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:55:54',
                'updated_at' => '2024-06-04 09:55:54'
            ],
            [
                'id' => 24,
                'emp_id' => 1,
                'name_ar' => 'سيارات',
                'name_en' => 'Cars',
                'parent_id' => 4,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 09:59:17',
                'updated_at' => '2024-06-04 09:59:17'
            ],
            [
                'id' => 25,
                'emp_id' => 1,
                'name_ar' => 'الموردين',
                'name_en' => 'Suppliers',
                'parent_id' => 7,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:03:22',
                'updated_at' => '2024-06-04 10:03:22'
            ],
            [
                'id' => 26,
                'emp_id' => 1,
                'name_ar' => 'النقدية',
                'name_en' => 'Cash',
                'parent_id' => 5,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:05:06',
                'updated_at' => '2024-06-04 10:05:06'
            ],
            [
                'id' => 27,
                'emp_id' => 1,
                'name_ar' => 'النقدية بالخزينة',
                'name_en' => 'Cash in the safe',
                'parent_id' => 26,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:05:48',
                'updated_at' => '2024-06-04 10:05:48'
            ],
            [
                'id' => 28,
                'emp_id' => 1,
                'name_ar' => 'النقدية بالبنك',
                'name_en' => 'Cash in the bank',
                'parent_id' => 26,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:06:35',
                'updated_at' => '2024-06-04 10:06:35'
            ],
            [
                'id' => 29,
                'emp_id' => 1,
                'name_ar' => 'العملاء',
                'name_en' => 'Customers',
                'parent_id' => 5,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:07:37',
                'updated_at' => '2024-06-04 10:07:37'
            ],
            [
                'id' => 30,
                'emp_id' => 1,
                'name_ar' => 'المخزون',
                'name_en' => 'Inventory',
                'parent_id' => 5,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:08:28',
                'updated_at' => '2024-06-04 10:08:28'
            ],
            [
                'id' => 31,
                'emp_id' => 1,
                'name_ar' => 'العدد والادوات',
                'name_en' => 'Equipment and tools',
                'parent_id' => 4,
                'type' => 0,
                'type_account' => 1,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:09:54',
                'updated_at' => '2024-06-04 10:09:54'
            ],
            [
                'id' => 32,
                'emp_id' => 1,
                'name_ar' => 'المقاولين',
                'name_en' => 'Contractors',
                'parent_id' => 7,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:11:47',
                'updated_at' => '2024-06-04 10:11:47'
            ],
            [
                'id' => 33,
                'emp_id' => 1,
                'name_ar' => 'القروض - طويله الاجل',
                'name_en' => 'Loans - long term',
                'parent_id' => 8,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:13:09',
                'updated_at' => '2024-06-04 10:13:09'
            ],
            [
                'id' => 34,
                'emp_id' => 1,
                'name_ar' => 'تمويل - طويل الاجل',
                'name_en' => 'Financing - long term',
                'parent_id' => 8,
                'type' => 0,
                'type_account' => 0,
                'value' => 0,
                'targete' => 0,
                'parent_targete' => 0,
                'parent_value' => 0,
                'status' => 0,
                'note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-06-04 10:13:43',
                'updated_at' => '2024-06-04 10:13:43'
            ]
        ]);
    }
}