<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContactsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contacts = [
            [
                'id' => 1,
                'emp_id' => 1,
                'social_id' => 3,
                'contractdr_id' => null,
                'typecont_id' => 2,
                'name_en' => 'contact 1',
                'phone' => '01005541337',
                'phone2' => null,
                'landline' => null,
                'address' => null,
                'birth_date' => null,
                'gender' => 0,
                'marital_status' => 0,
                'email' => null,
                'website' => null,
                'facebook' => null,
                'socialmedia' => null,
                'note' => null,
                'speciality_id' => '["2"]',
                'preferd_gift_brand' => 'null',
                'university_degree' => null,
                'scientific_degree' => null,
                'preferd_readding' => null,
                'preferd_gift' => null,
                'preferd_service' => null,
                'description' => '',
                'status' => 0,
                'deleted_at' => null,
                'created_at' => '2025-03-09 21:54:25',
                'updated_at' => '2025-03-09 21:54:25'
            ],
            [
                'id' => 2,
                'emp_id' => 1,
                'social_id' => 2,
                'contractdr_id' => null,
                'typecont_id' => 1,
                'name_en' => 'contact 2',
                'phone' => '01441132550',
                'phone2' => null,
                'landline' => null,
                'address' => null,
                'birth_date' => null,
                'gender' => 1,
                'marital_status' => 1,
                'email' => null,
                'website' => null,
                'facebook' => null,
                'socialmedia' => null,
                'note' => null,
                'speciality_id' => '["1"]',
                'preferd_gift_brand' => 'null',
                'university_degree' => null,
                'scientific_degree' => null,
                'preferd_readding' => null,
                'preferd_gift' => null,
                'preferd_service' => null,
                'description' => '',
                'status' => 0,
                'deleted_at' => null,
                'created_at' => '2025-03-09 21:55:31',
                'updated_at' => '2025-03-09 21:55:31'
            ],
            [
                'id' => 3,
                'emp_id' => 1,
                'social_id' => 4,
                'contractdr_id' => null,
                'typecont_id' => 1,
                'name_en' => 'contact 3',
                'phone' => '06618874991',
                'phone2' => null,
                'landline' => null,
                'address' => null,
                'birth_date' => '1989-03-02',
                'gender' => 0,
                'marital_status' => 2,
                'email' => null,
                'website' => null,
                'facebook' => null,
                'socialmedia' => null,
                'note' => null,
                'speciality_id' => '["3"]',
                'preferd_gift_brand' => 'null',
                'university_degree' => null,
                'scientific_degree' => null,
                'preferd_readding' => null,
                'preferd_gift' => null,
                'preferd_service' => null,
                'description' => '',
                'status' => 0,
                'deleted_at' => null,
                'created_at' => '2025-03-09 21:56:56',
                'updated_at' => '2025-03-09 21:56:56'
            ],
            [
                'id' => 4,
                'emp_id' => 1,
                'social_id' => 3,
                'contractdr_id' => null,
                'typecont_id' => 2,
                'name_en' => 'contact 4',
                'phone' => '08774136448',
                'phone2' => null,
                'landline' => null,
                'address' => null,
                'birth_date' => '1983-11-10',
                'gender' => 1,
                'marital_status' => 2,
                'email' => null,
                'website' => null,
                'facebook' => null,
                'socialmedia' => null,
                'note' => null,
                'speciality_id' => '["4","8"]',
                'preferd_gift_brand' => 'null',
                'university_degree' => null,
                'scientific_degree' => null,
                'preferd_readding' => null,
                'preferd_gift' => null,
                'preferd_service' => null,
                'description' => '',
                'status' => 0,
                'deleted_at' => null,
                'created_at' => '2025-03-09 21:58:23',
                'updated_at' => '2025-03-09 21:58:23'
            ],
            [
                'id' => 5,
                'emp_id' => 1,
                'social_id' => 4,
                'contractdr_id' => null,
                'typecont_id' => 3,
                'name_en' => 'contact 5',
                'phone' => '0446685447',
                'phone2' => null,
                'landline' => null,
                'address' => null,
                'birth_date' => '1982-12-19',
                'gender' => 1,
                'marital_status' => 0,
                'email' => null,
                'website' => null,
                'facebook' => null,
                'socialmedia' => null,
                'note' => null,
                'speciality_id' => '["6"]',
                'preferd_gift_brand' => 'null',
                'university_degree' => 'University Degree',
                'scientific_degree' => 'scientific Degree',
                'preferd_readding' => 'sports',
                'preferd_gift' => 'flowers - sweets',
                'preferd_service' => 'Alex Conference on rheumatology',
                'description' => '',
                'status' => 0,
                'deleted_at' => null,
                'created_at' => '2025-03-10 21:33:44',
                'updated_at' => '2025-03-10 21:34:30'
            ],
            [
                'id' => 6,
                'emp_id' => 1,
                'social_id' => 3,
                'contractdr_id' => null,
                'typecont_id' => 2,
                'name_en' => 'contact 6',
                'phone' => '0994475110',
                'phone2' => null,
                'landline' => null,
                'address' => null,
                'birth_date' => null,
                'gender' => 0,
                'marital_status' => 0,
                'email' => null,
                'website' => null,
                'facebook' => null,
                'socialmedia' => null,
                'note' => null,
                'speciality_id' => '["1","7"]',
                'preferd_gift_brand' => 'null',
                'university_degree' => null,
                'scientific_degree' => null,
                'preferd_readding' => null,
                'preferd_gift' => null,
                'preferd_service' => null,
                'description' => '',
                'status' => 0,
                'deleted_at' => null,
                'created_at' => '2025-03-10 21:40:30',
                'updated_at' => '2025-03-10 21:40:30'
            ],
        ];

        DB::table('contacts')->insert($contacts);
    }
}